apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-web-ingress
  namespace: portfolio
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: portfolio-web-ingress
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-web-svc
            port:
              number: 3000
